site_name: AutoFV_Framework

nav:
  - Home: index.md
  - Generate a Framework: GenerateFramework.md
  - Run Formal: RunFormal.md
  - Property Macros: PropertyMacros.md
  - FAQ: FAQ.md
  - Contributing: Contributing.md

theme:
  name: readthedocs